# Generated by Django 5.1.3 on 2024-11-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary_app', '0002_confirmationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebooksmodel',
            old_name='author',
            new_name='uploader',
        ),
        migrations.RenameField(
            model_name='ebooksmodel',
            old_name='author_id',
            new_name='uploader_id',
        ),
        migrations.AddField(
            model_name='ebooksmodel',
            name='author_name',
            field=models.CharField(default='Malik', max_length=80),
        ),
    ]
