# Generated by Django 5.1.3 on 2024-11-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary_app', '0003_rename_author_ebooksmodel_uploader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooksmodel',
            name='author_name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
