# Generated by Django 5.1.3 on 2024-11-25 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary_app', '0004_alter_ebooksmodel_author_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooksmodel',
            name='uploader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_ebooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
