# Generated by Django 5.1.3 on 2024-11-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary_app', '0005_alter_ebooksmodel_uploader_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebooksmodel',
            name='uploader',
        ),
    ]
